In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.8.0'

In [17]:
dataset=pd.read_csv("Churn_Modelling.csv")
X=dataset.iloc[:,3:-1].values
y=dataset.iloc[:,-1].values
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [4]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

## Encoding Categorical Data

Label Encoding the "Gender" column

In [5]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:,2]=le.fit_transform(X[:,2])

In [6]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [8]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


## Splitting the dataset into the training set and test set

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Feature Scaling

In [10]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [18]:
X.shape

(10000, 10)

## BUILDING ANN

Initialising ANN

In [11]:
ann=tf.keras.models.Sequential()

Adding input layer and the first hidden layer

In [12]:
# units determines hidden neuron...and this is determined experimentally or we can hit and trial method.....
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))

Adding input layer and the second hidden layer

In [13]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))

Adding output layer

In [14]:
# here in output we only need one unit as it is binary classification.....
# we know that every neuron holds a value...so if the value in o/p neuron 
# is less than threshold we will select a class or the other one
ann.add(tf.keras.layers.Dense(units=1,activation="sigmoid"))

## TRAINING THE ANN

Compiling the ANN

In [15]:
# now we will be passing few parameters inside our compile method.......
# now we will use loss="binary_crossentropy" as our classification is binary..
ann.compile(optimizer="adam",loss="binary_crossentropy", metrics=["accuracy"])

Training the ANN

In [16]:
ann.fit(X_train,y_train,batch_size=32, epochs=500)

Epoch 1/500
250/250 [==============================] - 1s 868us/step - loss: 0.5526 - accuracy: 0.7960
Epoch 2/500
250/250 [==============================] - 0s 895us/step - loss: 0.4911 - accuracy: 0.7960
Epoch 3/500
250/250 [==============================] - 0s 886us/step - loss: 0.4538 - accuracy: 0.8046
Epoch 4/500
250/250 [==============================] - 0s 910us/step - loss: 0.4342 - accuracy: 0.8141
Epoch 5/500
250/250 [==============================] - 0s 907us/step - loss: 0.4253 - accuracy: 0.8195
Epoch 6/500
250/250 [==============================] - 0s 1ms/step - loss: 0.4199 - accuracy: 0.8255
Epoch 7/500
250/250 [==============================] - 0s 917us/step - loss: 0.4157 - accuracy: 0.8257
Epoch 8/500
250/250 [==============================] - 0s 899us/step - loss: 0.4132 - accuracy: 0.8267
Epoch 9/500
250/250 [==============================] - 0s 905us/step - loss: 0.4111 - accuracy: 0.8256
Epoch 10/500
250/250 [==============================] - 0s 897us/step - los

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "C:\Users\anura\AppData\Roaming\Python\Python310\site-packages\IPython\core\interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\anura\AppData\Local\Temp/ipykernel_3896/2906315515.py", line 1, in <module>
    ann.fit(X_train,y_train,batch_size=32, epochs=500)
  File "C:\Users\anura\AppData\Roaming\Python\Python310\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
    return fn(*args, **kwargs)
  File "C:\Users\anura\AppData\Roaming\Python\Python310\site-packages\keras\engine\training.py", line 1376, in fit
    for step in data_handler.steps():
  File "C:\Users\anura\AppData\Roaming\Python\Python310\site-packages\keras\engine\data_adapter.py", line 1246, in steps
    original_spe = self._steps_per_execution.numpy().item()
  File "C:\Users\anura\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 674, in numpy
   

TypeError: object of type 'NoneType' has no len()

## Part 4 - Making the predictions and evaluating the model

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

In [ ]:
# predict must always be a 2d array.....
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))>0.5)
# if u want value then...
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])>0.5))

Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [ ]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

### Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)